# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hdfs.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'hdfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhdfs.proto\x12\x04hdfs\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1b\n\x07\x42lockID\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"+\n\tBlockData\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"6\n\x0e\x42lockLocations\x12\x11\n\tblock_ids\x18\x01 \x03(\t\x12\x11\n\tdatanodes\x18\x02 \x03(\t\"\x1d\n\x08\x46ileList\x12\x11\n\tfilenames\x18\x01 \x03(\t\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x9f\x01\n\x08NameNode\x12\x35\n\nCreateFile\x12\x11.hdfs.FileRequest\x1a\x14.hdfs.BlockLocations\x12\x32\n\x07GetFile\x12\x11.hdfs.FileRequest\x1a\x14.hdfs.BlockLocations\x12(\n\tListFiles\x12\x0b.hdfs.Empty\x1a\x0e.hdfs.FileList2a\n\x08\x44\x61taNode\x12(\n\nWriteBlock\x12\x0f.hdfs.BlockData\x1a\t.hdfs.Ack\x12+\n\tReadBlock\x12\r.hdfs.BlockID\x1a\x0f.hdfs.BlockDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hdfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=20
  _globals['_FILEREQUEST']._serialized_end=51
  _globals['_BLOCKID']._serialized_start=53
  _globals['_BLOCKID']._serialized_end=80
  _globals['_BLOCKDATA']._serialized_start=82
  _globals['_BLOCKDATA']._serialized_end=125
  _globals['_BLOCKLOCATIONS']._serialized_start=127
  _globals['_BLOCKLOCATIONS']._serialized_end=181
  _globals['_FILELIST']._serialized_start=183
  _globals['_FILELIST']._serialized_end=212
  _globals['_ACK']._serialized_start=214
  _globals['_ACK']._serialized_end=235
  _globals['_EMPTY']._serialized_start=237
  _globals['_EMPTY']._serialized_end=244
  _globals['_NAMENODE']._serialized_start=247
  _globals['_NAMENODE']._serialized_end=406
  _globals['_DATANODE']._serialized_start=408
  _globals['_DATANODE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
